# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "91d3922ce95b34d51a8f3a85dfd5c117"
name = "OutletX MVP"
handle = "outletx-dev"
application_url = "https://outletx.io/app/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,read_products,write_products,read_inventory"

[access.admin]
embedded_app_direct_api_access = true

[auth]
redirect_urls = [
  "https://outletx.io/api/auth/callback/"
]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled","products/create","products/delete","products/update","orders/fulfilled"]
uri = "https://outletx.io/api/webhooks/"

[pos]
embedded = false