# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "345807df431aedc80af38c5c45ef2ecb"
name = "OutletX MVP"
handle = "my-awesome-app-155"
application_url = "https://shall-adjacent-towns-virtually.trycloudflare.com/app/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,read_products,write_products,read_inventory"

[access.admin]
embedded_app_direct_api_access = true

[auth]
redirect_urls = [
  "https://shall-adjacent-towns-virtually.trycloudflare.com/api/auth/callback/"
]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled","products/create","products/delete","products/update","orders/fulfilled"]
uri = "https://shall-adjacent-towns-virtually.trycloudflare.com/api/webhooks/"

[pos]
embedded = false