import fs from 'fs';
import toml from 'toml';

// Define the list of environment variables to process
const keysToProcess = ['SHOPIFY_API_KEY'];

const filePath = '../shopify.app.toml';
const envPath = '../.env';

const tomlString = fs.readFileSync(filePath, 'utf-8');
const parsedConfig = toml.parse(tomlString);
const envString = fs.readFileSync(envPath, 'utf-8');
const envVariables = {};
const lines = envString.trim().split('\n');

lines.forEach(line => {
  const [key, value] = line.split('=');
  if (keysToProcess.includes(key) && value !== undefined) {
    envVariables['VITE_' + key.trim()] = value.trim();
  }
});

envVariables['VITE_SHOPIFY_APP_HANDLE'] = parsedConfig.handle;

fs.writeFileSync('.env', ['// This file was generated by prebuild.js', ...Object.entries(envVariables).map(([key, value]) => `${key}=${value}`)].join('\n'));